### PR TITLE
Fix cron user

### LINKED ISSUE #39: Cron "cleanFiles", "cleanBdd" and "watch" fails
I'm receiving mails from `www-data@domain.tld` for each of these cron:

> Can't load application from file "/var/www/lufi/script/../script/application": The upload directory (files) is not writable at lib/Lufi.pm line 80, <DATA> line 755.
> Compilation failed in require at (eval 106) line 1, <DATA> line 755.
>

### PR DESCRIPTION
**Pull request by autra**
Lufi has its own user for the web service, it should also use it in the installed cron.

Fixes #39 

notifying @YunoHost-Apps/apps-group (I hope it's the correct group :-) )

### CODE REVIEW

**Comment by maniackcrudelis** [comment]
I do agree with that PR.
But why do you notify the apps group ?

**Comment by autra** [comment]
>  But why do you notify the apps group ?

dunno it seems a good group for an app review, but maybe I'm wrong :-)

**Comment by maniackcrudelis** [comment]
Hum... yes for sure we could. But we usually don't because there's over 300 apps :wink: 

Did you try your PR with package_check ?

**Comment by autra** [comment]
>  But we usually don't because there's over 300 apps 

Understood. Sorry for that!



> Did you try your PR with package_check ?

[yep I did](https://ci-apps-dev.yunohost.org/jenkins/view/all/job/lufi_ynh%20(autra)/)

**Comment by maniackcrudelis** [comment]
Don't be sorry for that.
Just if you need anything specifically, ask for it.

We may have a look to some specific apps if you need help. Otherwise, we usually don't because we already have a lot to do.
So your test gave a level 7, quite good already.
If there any point in the log that you're wondering about, don't hesitate to ask.

**Comment by kay0u** [comment]
Yolomerging in testing

**Pull request merged**
