### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by kay0u**
Fix https://github.com/YunoHost-Apps/lufi_ynh/issues/39

### CODE REVIEW

**Comment by Tagadda** [comment]
LGTM.
I'll do a PR for 0.04.6 but this can wait for the next testing, we need to merge this as it create a false negative in the 3.8 diagnostics.

**Comment by Tagadda** [comment]
We need to increase version to `0.03.5~ynh2` or something ?

**Comment by kay0u** [comment]
Yup, I'm trying to install it before merging

**Comment by kay0u** [comment]
It works! Merging

**Pull request merged**
