### PR TITLE
Allow LDAP on public and remove legacy permission and various fixes

### LINKED ISSUE #68: Feature request: Allow installing with LDAP and without being invisible to anonymous
### Describe the feature request

*I want to be able to install Lufi with LDAP user but without making Lufi not visible from anonymous. I also don't see the use case of needing to log in two times to access Luti.*

### Context

- Hardware: *Old laptop or computer*
- YunoHost version: 4.3.6
- I have access to my server: *Through SSH | through the webadmin | direct access via keyboard / screen | ...*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*

- Using, or trying to install package version/branch: master/stable
- If upgrading, current package version: *can be found in the admin, or with `yunohost app info $app_id`*

Edit: I'm actually trying to make the package work without legacy permissions.

### PR DESCRIPTION
**Pull request by tytan652**
## Problem

Closes #68 

I wanted to allow installing Luti with LDAP with public visibility and remove legacy permission.

## Solution
- I ask on install if the user wants to enable LDAP.
- I put the LDAP user filter from the [documentation](https://yunohost.org/en/packaging_apps_permissions) in Lufi config.
- I upgrade permissions depending on if `is_public` or legacy permission still exists.

## Other changes
- I replaces `ynh_replace_string` usage by `ynh_add_config`.
- I removed the deprecated redirect in nginx config.
- I bumped the package version.

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)
  - I at least try to install and remove it on my machine.
  - I also tried the user filter and it works.

summary

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
!testme

**Comment by tytan652** [comment]
I was actually rebasing but you fix the conflicts.

Note: Tabs have to be replaced by spaces in the `manifest.json` if needed.

**Comment by yalh76** [comment]
> I was actually rebasing but you fix the conflicts.
Yes, as I've done few modifications without checking your PR, I'd prefer to fix the mess

> 
> Note: Tabs have to be replaced by spaces in new lines of the `manifest.json` if needed.
I've seen that and done it :)

Just have to wait for the package_check and we will merge it in testing

**Pull request merged**
