### PR TITLE
systemd service type should be "forking" ?

### PR DESCRIPTION
**Pull request by alexAubin**
c.f. discussion in https://github.com/YunoHost/yunohost/pull/941#discussion_r415075456 , and https://framagit.org/fiat-tux/hat-softwares/lufi/-/blob/master/utilities/lufi.service#L8 (credit to autra for finding this )

### CODE REVIEW

**Comment by ldidry** [comment]
Note: The same problem exists on https://github.com/YunoHost-Apps/lstu_ynh/blob/master/conf/systemd.service and https://github.com/YunoHost-Apps/lutim_ynh/blob/master/conf/systemd.service

**Comment by autra** [comment]
You need to fix another bug at the same time:

`PIDFile=__FINALPATH__script/hypnotoad.pid` should be PIDFile=__FINALPATH__/script/hypnotoad.pid. Systemd cannot find the pid file because of that. For simple unit, systemctl start still returns because it does so just after forking the main service process, but with forking it's not the case any more and it will hang forever.

Also according to my test, `RemainOnExit` should be removed to report correct status when children fail, also I'm pretty sure it's a systemd bug that got resolved on later version (but I still need to test this to be sure).

**Comment by autra** [comment]
> `PIDFile=__FINALPATH__script/hypnotoad.pid` should be `PIDFile=__FINALPATH__/script/hypnotoad.pid`

I did it here: https://github.com/YunoHost-Apps/lufi_ynh/pull/37

**Comment by autra** [comment]
> Also according to my test, `RemainOnExit` should be removed to report correct status when children fail, also I'm pretty sure it's a systemd bug that got resolved on later version (but I still need to test this to be sure).

Testing done, in all cases, for a forking unit spawning a daemon (which is the case here if I'm not mistaken), RemainOnExit should be set to no (the default value).

I did that here: https://github.com/YunoHost-Apps/lufi_ynh/pull/38

**Comment by kay0u** [comment]
Yolomerging in testing

**Pull request merged**
